baseURL = "https://yordrar.github.io/"
languageCode = "en-us"
theme = "sada"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    name = ""
    title = "Juan Antonio Hern치ndez C치novas"
    author = "Darshan Baral"
    description = "Game Programmer at Codemasters"
    copyright = ""
    theme = "light" # `dark` or `light`
    useResources = false

    # Profile section
    [params.profile]
        name = "Juan Antonio Hern치ndez C치novas"
        photo = "images/profile.png"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
        icon = "fab fa-github"
        url = "https://github.com/Yordrar"
        title = "GitHub"

        [[params.social.list]]
        icon = "fab fa-linkedin-in"
        url = "https://www.linkedin.com/in/ja-hernandezc/"
        title = "LinkedIn"
		
		[[params.social.list]]
        icon = "fab fa-twitter"
        url = "https://twitter.com/Yordrar"
        title = "Twitter"
		
		[[params.social.list]]
        icon = "fas fa-envelope"
        url = "mailto:juanantoniohernandezcanovas@gmail.com"
        title = "Mail"		

    # Education section
    [params.education]
        title = "Education"

        [[params.education.list]]
        degree = "BSc in Computer Science"
        college = "University of Murcia, Spain"
        dates = "2016 - 2020"
        thesis_title = "Design and Implementation of a rendering system using advanced pathtracing techniques"
        thesis_link = "https://github.com/Yordrar/thesis-raytracer"

    # Languages section
    [params.language]
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Upper-Intermediate (B2)"
				
        [[params.language.list]]
        language = "Spanish"
        level = "Native"

    # Interests section
    [params.hobbies]
        title = "Interests"

        [[params.hobbies.list]]
        interest = "Sci-fi / Fantasy books"
		
		[[params.hobbies.list]]
        interest = "Videogames"

        [[params.hobbies.list]]
        interest = "Graphics programming"

        [[params.hobbies.list]]
        interest = "Game engine architecture"

    [params.aboutme]
        description = "I am a programmer interested in graphics and gamedev. I began learning about graphics when I developed my bachelor's thesis, which is a software pathtracer. I am now working at Codemasters as a gameplay programmer."

    # Experiences section
    [params.experiences]
        title = "Experiences"

        [[params.jobs.list]]
        position = "Gameplay Programmer"
        dates = "Nov 2020 - *Present*"
		link = "https://www.codemasters.com/"
        company = "Codemasters"
        details = ""

        [[params.jobs.list]]
        position = "Intern Programmer"
        dates = "Feb 2019 - Apr 2019"
		link = "https://sonsofabit.com/"
        company = "Sons of a Bit"
        details = "I worked as a programmer in the development of a mobile game using the Unity game engine and C#."

    # Projects section
    [params.projects]
        title = "Projects"

        [[params.projects.list]]
        title = "C++ Pathtracer"
        url = "https://github.com/Yordrar/thesis-raytracer"
        description = "A software pathtracer I developed for my bachelor's thesis as a way to begin learning about graphics programming. Because of this, it is coded in pure C++ with no graphics API. This allowed me to learn deeply about graphics and raytracing topics, such as BVHs, importance sampling and Monte Carlo."
		
		[[params.projects.list]]
        title = "Model Viewer"
        url = "https://github.com/Yordrar/d3d_model_viewer"
        description = "A simple model viewer I developed primarily to learn DirectX 11 and PBR."
        
        [[params.projects.list]]
        title = "Marching Cubes demo"
        url = "https://github.com/Yordrar/marching-cubes-demo"
        description = "A simple demo I developed in C++ and DirectX 11 to play around with the marching cubes algorithm."
